Do not run AppleScript-based Finder prettification if running in Sandbox

diff --git a/create-dmg b/create-dmg
--- a/create-dmg
+++ b/create-dmg
@@ -346,31 +346,36 @@ if [[ -n "$ADD_FILE_SOURCES" ]]; then
 	done
 fi
 
-# Run applescript
+# Run AppleScript to do all the Finder cosmetic stuff
 APPLESCRIPT_FILE=$(mktemp -t createdmg.tmp.XXXXXXXXXX)
-
-if [[ $SKIP_JENKINS -eq 0 ]]; then
-	cat "$CDMG_SUPPORT_DIR/template.applescript" \
-		| sed -e "s/WINX/$WINX/g" -e "s/WINY/$WINY/g" -e "s/WINW/$WINW/g" -e "s/WINH/$WINH/g" -e "s/BACKGROUND_CLAUSE/$BACKGROUND_CLAUSE/g" \
-				-e "s/REPOSITION_HIDDEN_FILES_CLAUSE/$REPOSITION_HIDDEN_FILES_CLAUSE/g" -e "s/ICON_SIZE/$ICON_SIZE/g" -e "s/TEXT_SIZE/$TEXT_SIZE/g" \
-		| perl -pe  "s/POSITION_CLAUSE/$POSITION_CLAUSE/g" \
-		| perl -pe "s/QL_CLAUSE/$QL_CLAUSE/g" \
-		| perl -pe "s/APPLICATION_CLAUSE/$APPLICATION_CLAUSE/g" \
-		| perl -pe "s/HIDING_CLAUSE/$HIDING_CLAUSE/" \
-		> "$APPLESCRIPT_FILE"
-	sleep 2 # pause to workaround occasional "Can’t get disk" (-1728) issues  
-	echo "Running AppleScript: /usr/bin/osascript \"${APPLESCRIPT_FILE}\" \"${VOLUME_NAME}\""
-	if /usr/bin/osascript "${APPLESCRIPT_FILE}" "${VOLUME_NAME}"; then
-		# Okay, we're cool
-		true
-	else
-		echo >&2 "Failed running AppleScript"
-		hdiutil detach "${DEV_NAME}"
-		exit 64
+if [[ $SANDBOX_SAFE -eq 1 ]]; then
+	echo "Skipping Finder-prettifying AppleScript because we are in Sandbox..."
+else
+	if [[ $SKIP_JENKINS -eq 0 ]]; then
+		cat "$CDMG_SUPPORT_DIR/template.applescript" \
+			| sed -e "s/WINX/$WINX/g" -e "s/WINY/$WINY/g" -e "s/WINW/$WINW/g" \
+					-e "s/WINH/$WINH/g" -e "s/BACKGROUND_CLAUSE/$BACKGROUND_CLAUSE/g" \
+					-e "s/REPOSITION_HIDDEN_FILES_CLAUSE/$REPOSITION_HIDDEN_FILES_CLAUSE/g" \
+					-e "s/ICON_SIZE/$ICON_SIZE/g" -e "s/TEXT_SIZE/$TEXT_SIZE/g" \
+			| perl -pe "s/POSITION_CLAUSE/$POSITION_CLAUSE/g" \
+			| perl -pe "s/QL_CLAUSE/$QL_CLAUSE/g" \
+			| perl -pe "s/APPLICATION_CLAUSE/$APPLICATION_CLAUSE/g" \
+			| perl -pe "s/HIDING_CLAUSE/$HIDING_CLAUSE/" \
+			> "$APPLESCRIPT_FILE"
+		sleep 2 # pause to workaround occasional "Can’t get disk" (-1728) issues  
+		echo "Running AppleScript to make Finder stuff pretty: /usr/bin/osascript \"${APPLESCRIPT_FILE}\" \"${VOLUME_NAME}\""
+		if /usr/bin/osascript "${APPLESCRIPT_FILE}" "${VOLUME_NAME}"; then
+			# Okay, we're cool
+			true
+		else
+			echo >&2 "Failed running AppleScript"
+			hdiutil detach "${DEV_NAME}"
+			exit 64
+		fi
+		echo "Done running the AppleScript..."
+		sleep 4
+		rm "$APPLESCRIPT_FILE"
 	fi
-	echo "Done running the AppleScript..."
-	sleep 4
-	rm "$APPLESCRIPT_FILE"
 fi
 
 # Make sure it's not world writeable
