Codesign option
https://github.com/create-dmg/create-dmg/issues/126

diff --git a/create-dmg b/create-dmg
--- a/create-dmg
+++ b/create-dmg
@@ -26,6 +26,7 @@ SANDBOX_SAFE=0
 BLESS=0
 SKIP_JENKINS=0
 MAXIMUM_UNMOUNTING_ATTEMPTS=3
+SIGNATURE=""
 
 function pure_version() {
 	echo "$CDMG_VERSION"
@@ -84,6 +85,8 @@ Options:
       execute hdiutil in quiet mode
   --bless
       bless the mount folder (deprecated, needs macOS 12.2.1 or older)
+  --codesign-signature
+      codesign the final disk image with the specified signature
   --sandbox-safe
       execute hdiutil with sandbox compatibility and do not bless
   --version
@@ -172,6 +175,9 @@ while [[ "${1:0:1}" = "-" ]]; do
 		--hdiutil-quiet)
 			HDIUTIL_VERBOSITY='-quiet'
 			shift;;
+		--codesign-signature)
+			SIGNATURE="$2"
+			shift; shift;;
 		--sandbox-safe)
 			SANDBOX_SAFE=1
 			shift;;
@@ -486,6 +492,18 @@ else
 		hdiutil internet-enable -yes "${DMG_DIR}/${DMG_NAME}"
 	else
 		echo "hdiutil does not support internet-enable. Note it was removed in macOS 10.15."
+	fi
+fi
+
+if [[ -n "${SIGNATURE}" && "${SIGNATURE}" != "-null-" ]]; then
+	echo "Codesign started"	
+	codesign -s "${SIGNATURE}" "${DMG_DIR}/${DMG_NAME}"
+	dmgsignaturecheck="$(codesign --verify --deep --verbose=2 --strict "${DMG_DIR}/${DMG_NAME}" 2>&1 >/dev/null)"
+	if [ $? -eq 0 ]; then
+		echo "The image is now codesigned"
+	else
+		echo "The signature seems invalid${NC}"
+		exit 1
 	fi
 fi
 
